[default]
_pulse_classname = "Pulse"
_pulse_apptype = "background"
_pulse_origin = "https://github.com/touchpi/touchpi"

_pulse_in_second = 1
_pulse_factors = [1, 3, 60, 300]

[development]

[production]

